apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KGz4IpHkScK4wudyRS8yBrlAmY4QO1djlPmA3KyBQIAoGxpz,iv:Kfo4/1ZDHZUy5xWkbXqd4r96xyssywm9z3OYpdNGqm4=,tag:fDfNZ94fDCGrbok7NUOG6g==,type:str]
    credentials.json: ENC[AES256_GCM,data:r0rf9FvDaKfnA2NxpnQ33EUEJ/oXjK4Ay8HFwEJmTmD7+iLnYMCC9g4UCQM+9MdjJZOkqC1xowP5cAEDRPNRvwu9QViWi7TEt33SU4vE7a1aVqejX0y4oS5HiItgQa5GO7CZzteoduNa37uPSL6+/JMOtzOdMZlo9glbqOknXyuDSUHKmgBt4T0VfSbPkJiQhNS2YaDpQalSPRWFTlqop76JXpvtFwdog885+JteDg==,iv:mHXNFYEuhtvQCJ5YoZrofuj9dcLzWlKDuNPlsM7Bh9I=,tag:8qAZ1Eg89UgbWEEHj7tcSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTG9Rano1WUZCb2IvSUZB
            MG80RS8rWEZlcGtEZmk1ZUU3UGlFVUI4VUZVCmloOWwvdWxFTkJoeUlmSHJiMEkw
            WSt5KzU3ejlFSTRSaGNvc1orbGZ0OTAKLS0tIC9BU1M0cjB3NEE2RmFGT3kvWjNx
            RE1palA3eFFSbjNSREt2UGdsQUJtZGMKanwm+aPO4q3q+hND3rgnQ+HCtQmRHs0g
            40lQA433evyO0oyiMUW3LWF4lt5DZWXId9zL3l1IVpawLAQ1cONslA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T21:38:44Z"
    mac: ENC[AES256_GCM,data:5dtz13H9mk9IMc1kkt67ZQ6McTBRRwwPvuU40iiTIqnjb8Rg6Zkv/rsoTNyNHbjk5g/GMeu+BEqyOT8+RZmiYTzZ7fzRiTyH484RiNrm1o3LI6xu75KBAIEbE+juegYGPNyhwXa/KKS3RDQPz+zFHBJQzpKedUK/XgdPHjhvhNw=,iv:cTqEqfUlrv45eJPMB8caUPZwsGsTaO1sSQl+AzmfVys=,tag:2zI4tVF020BxcMdSDhMYDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
