apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 8.5.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    replicas: 1

    env:
      - name: GF_DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: grafana-db-connection-secret
            key: DB_USER
      - name: GF_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: grafana-db-connection-secret
            key: DB_PASSWORD

    automountServiceAccountToken: true

    deploymentStrategy:
      type: RollingUpdate

    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 120
      timeoutSeconds: 30
      periodSeconds: 20
      failureThreshold: 10

    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 120
      timeoutSeconds: 30
      failureThreshold: 10

    image:
      registry: docker.io
      repository: grafana/grafana
      tag: "11.2.3"
      pullPolicy: IfNotPresent

    createConfigmap: true
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 3000
      portName: service

    serviceMonitor:
      enabled: true
      path: /metrics
      interval: 30s
      scrapeTimeout: 30s

    ingress:
      enabled: true
      ingressCLassName: internal

      annotations:
        kubernetes.io/ingress.class: internal
        kubernetes.io/tls-acme: "true"

      hosts:
        - "grafana.${SECRET_DOMAIN}"

      path: /
      pathType: Prefix

      tls:
        - secretName: grafana-tls
          hosts:
            - "grafana.${SECRET_DOMAIN}"

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    persistence:
      type: pvc
      enabled: true
      storageClassName: "openebs-hostpath"
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      finalizers:
        - kubernetes.io/pvc-protection
      lookupVolumeName: true

    adminUser: admin
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    #datasources:
    #  datasources.yaml:
    #    apiVersion: 1
    #    datasources:
    #      - name: PostgreSQL
    #        type: postgres
    #        access: proxy
    #        url: grafana-db-service.observability.svc.cluster.local:5432
    #        database: grafana
    #        user: ${GF_DATABASE_USER}
    #        secureJsonData:
    #          password: ${GF_DATABASE_PASSWORD}
    #        jsonData:
    #          sslMode: "disable"

    notifiers: {}
    dashboardProviders: {}
    dashboards: {}
    grafana.ini:
      #database:
      #  type: postgres
      #  host: grafana-db-service.cnpg-system.svc.cluster.local:5432
      #  name: grafana
      #  user: ${DB_USER}
      #  password: ${DB_PASSWORD}
      #  ssl_mode: "disable"
      #existingSecret: grafana-db-connection-secret

      paths:
        data: /var/lib/grafana/
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: true
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      server:
        domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else }}''{{ end }}"

    revisionHistoryLimit: 10
