apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:eyvkMwqXE5M=,iv:2XHymkJ37UfwvWaZeqALlkWopNA0sS3phjSM1xpsIuk=,tag:C0nLMxYWFw4X2MbNaIojZg==,type:str]
    admin-password: ENC[AES256_GCM,data:Xf8zDwR6hXhQbV2wvm85bX6SWUhkeURCKkidvbDAU9h+S68qpEd1hQ==,iv:feHKvQAwcYSzjOgL6o18iJVYlF504Vw/r4Hb8N+k0JM=,tag:ie40NdGE/hFEdDeNregw8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXlFdWU1WkRrZWVNbG1w
            dnpIeVpXY3pWWVFzQWtSeE4vaXB2Y0xSQkRrCjhIdnhjcnA2Y1pBc1A2YkhtUGhv
            SHFtcitXTVJRQWsrVlIxcXlwNmZ1eFUKLS0tIFZFeXlUQmZqNk14SmZJK2t4by9j
            eDZpNWVISkEzRUN2dzVFaVVLNDRQOVEK+hlQEhMtnTF4TmZ+HKwfb/nBNdS7nWnX
            WUD7qXXzAont4yH5azlC0O0mLcJgFsrOomHgCznJh1ODJec1SbIJSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T13:01:05Z"
    mac: ENC[AES256_GCM,data:f1OGILkpA1HMwZu5LiLC50e8xjgophv4mtDNToLWIwm2x/zVpjIyi16AfucYO0hHojmtkcKZtjJnzJs3VSeN8yxOiwuUTucZsR7JF8l040DEI5NXuXj03jF5SYA8leYCLdTIzMP0JCN6nvZwMjcAPY8a7ItyzyLJhai5Ps99Pl4=,iv:A5TvEyPWNwgLSQjyPoBSISkMPbpasuIgRB+Iam5t5uk=,tag:i5yNCM5X0+AhT7xZ4L8guQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
