apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9ObZK0n71VJMXGKkfhhtJ3VqifnBWw2d7TZPfCQYhd9xIPjbKqJQxQ==,iv:IjZ/y2Gd2uXNlCIMEIOH8C4uSt0djEyQ1iJ9+td/pa4=,tag:g2nBtKkdFX9hg/Zq4fFEew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydThuRDNhckdkem1FV1lz
            ZVpqQ3VKTVlUdkl3TkhSVnp0S1Vja2lxRUdFCnpKclE0ZWFrSjVYcFVsaGVybFZH
            Qno2SjZ4dTk1OTd4NGJJV0w3eTNlYjQKLS0tIDJCTkM0b3RlNDltUExIaW5qQkcw
            Z0loQjBTSjBFQndCV1ZLUFhLOUswTUUKh82VJVtoh6Wlodm+ktc+zbLjJbJCeB5t
            xl7Rzpvdu1LvM6USLT0/T9nINFKZj9Vz2gis3VaGhhra7G4LAw9sXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T08:04:04Z"
    mac: ENC[AES256_GCM,data:YrqM6jmrNXp5It7xfQvvzNTvwq1RQWiFmQmL3qiyDTlT8WgkDnmiN5Skr+lHovcumMy5jwX9eEY8tW9ydui7h4I+x7D1rMCSbGHZCdthoPBi6kQNuGsA9t56KUzlllKJykEwrizp5uKzEwwW4TbcSmn+6MrLN20Qz3QkbCrlagg=,iv:G2rrM3HJ/ZPRiBF7wK1bmu8SdEmjVdfaaiix6uXxToA=,tag:6/4ZLgkr1gbnM7Sax5veBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
