---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ./grafana-db/ks.yaml
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  #- ./prometheus/ks.yaml
