apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RO8XrCsA0MG1,iv:wGtDbN2ar+TYJPyCRDto8xilNtfDKdI+GjMwVPmn3ks=,tag:nA4ossG9xlL9XXNoUK99Eg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:puDeupM6wFAOF/tHthhnZyGeXXQ=,iv:9EOgNu66khizm7wpQ8xEe3VR4Vvcf0GtferAM5UxvGw=,tag:nzqkdptJwCJgIaixo5Nc1w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pW125/B3qHZhNAvd8VNoGEkQkrJ4J/1NuPHMFpqdqnPhqL8y,iv:EGI52Di3mRuz4w3b7GouWvq5TDAFntFt6cYzqQH4Db8=,tag:LtmFgL+Q6HuyyxDLHeq0pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbjZabHU0bHc2RDNxaEFW
            ZkU5b3ExN2RhTmtrd1dqTDBEWEpvRTgwNWdzCnlORmlmV1BoNmp6RjVpZ0VZY1ZU
            akZxMFQ3S211WDZMNEd5NExMbldPOWsKLS0tIFpmc2JNbm4vUGdhZytqY3R4Y3dr
            WlY4ZHdMd1U2TStVKzcxVGliRTliWjgKmQXVfE6tmYpU+ghjLgxIhazZzi80G0Cp
            DCJZMBd3W9yVPrRt0y3VLCGl0TtQjuubkwi8HFoihEevcocGwFhTtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T10:41:06Z"
    mac: ENC[AES256_GCM,data:JO2DGRjKPZDjacGZt1QYPf2pl0A+SKDyPMUB0HluYr+5EIKxxF5zqGrBe0OLJekBJlVW+DUIbVjTzt+rxjv3G1uNOl55I7LVwJEMXuhmvlR61H7bgRi7gU3bDbrbWwOWjKSyhaMt22ezaf8l3tFoCTDQ356CBvHxYmo9/fcyFuQ=,iv:ysATl8zhW3f3AHRgeT7duZscI/LcxxvIu3dwrSnZ8Fk=,tag:1+BCxnxbqtXcN84n/A17qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
