apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iTJzh9Nfxafp,iv:2LW3o63zvC1DAu8F5l047PVOop6ITZp7583G9H3rZ7M=,tag:kge7uveV5vz2sXwCjub4Ow==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:gB5TSG+otcVPOp7Yrc1yWvbFd+s=,iv:rt0gZ9eZvnvoGWCBAUvCalGSi7V8nlrrDb/se0Gl5i8=,tag:z1O3hANOrwQc9/oTSPbpgw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bBkra1DjmxxouIjEi4usQ87c1ab1lt3Ljt7wW6oNGVC1oKfn,iv:gOiQMFbXaDJLeniScTIUa7MikEenWzv43JLtainDDgw=,tag:Kl5fwyoqca5lDMd165F2WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NUJEYUtWZ0hTWXJ3SnZi
            VnRPdjhtdHJZS0k2VUhtSXp6YkhXdHVsekRjCkg4MDcvYjlTNWVaSHllODZoMXlC
            WmM3aG5aSnpxT0JPTUVhNzg1ckdEbXcKLS0tIG8vWXpzS1UxUm9vN0k5MGt6bWMx
            d2pNQkNwUWF6ZjVXbitiQWQwYVVBOG8KgL0Wptq4lQRTkVBx73oB2TVN4C6ly4tG
            s1lAga2EXS5G3oBVPFXPAlvNiL3KrT1OoDZpdQhUsWVBHQoQkHF4WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T10:09:50Z"
    mac: ENC[AES256_GCM,data:5mXcgvHDJdgrw+4nEgcJ1uUcCacQ5s+pLNahhE1XkoBzhJKo0ymbxu+Y7ws6AgxeiVlNvsIucP4eT4Nt+eAOgpYisTg3oprezhoFJWWWjXguInX19K2ue//kou5m2wCjvMJoy6TkJII+/IGeI3vFi3IcdOHtDiE1E4MZDR0uTdc=,iv:QmzllQ4IcF3z6GPQN7YtrWs7DGgXkQ+l8pNtkxEprEE=,tag:MNX0yEubUnMsGiIdL2Fi4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
