---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-grafana-db
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    storageClass: openebs-hostpath
    size: 5Gi
  walStorage:
    storageClass: openebs-hostpath
    size: 5Gi
