apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-secret
    namespace: observability
type: Opaque
data:
    GF_PASSWORD: ENC[AES256_GCM,data:WLzGZAXCLj4iA9j+0tDso6ky5spA6NMUtoGoL9OedcFG,iv:egxLVgADt+y6P7QvX4b26CKd8ZwhXmkvGOj90qZFkxs=,tag:IQ8H7dhNAlxZBgSA8mdEkw==,type:str]
    GF_DB_USER: ENC[AES256_GCM,data:bsAmsHBNU4Lf3RTZ,iv:g5qF/oV96VKezd2gBj68jGxJ5m12YM200OKN3cud49Q=,tag:nYv3Y1wKzGQSly/FnGAH+w==,type:str]
    password: ENC[AES256_GCM,data:VfF+xKyKcHWyiLFCrN8dqQf/ke7U2yslxwlJt5KW1GLr37UTUhcIDyhsf7u/1HtB,iv:ntfGjGAIZ75jR7QYr7WagXnxeEuM0w97uUDg+jy4qT8=,tag:vvClSu7dOKpsWDfQnlH4vA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Y6aTR1iVAwzWwiELwi3BRmMt9D8XlQ7Fdw6Z+xdZnns7YTQoYenb5mdIoaw0fZQs,iv:NLJMNm1C/LEPMkD/aLncqcYsFb5ZOOkRQxIE7ZgEjx8=,tag:9i+VYP2R+yBGLgxEvc7SJQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:E86nGJgbglwbjVPKrMrtzF2kTog=,iv:c/JdTw00wqvt+o8TFim4GdAOxZb2AuXHjTE2RAGMLTM=,tag:kIu/GMKABeB9hhj2bduAAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXlFdWU1WkRrZWVNbG1w
            dnpIeVpXY3pWWVFzQWtSeE4vaXB2Y0xSQkRrCjhIdnhjcnA2Y1pBc1A2YkhtUGhv
            SHFtcitXTVJRQWsrVlIxcXlwNmZ1eFUKLS0tIFZFeXlUQmZqNk14SmZJK2t4by9j
            eDZpNWVISkEzRUN2dzVFaVVLNDRQOVEK+hlQEhMtnTF4TmZ+HKwfb/nBNdS7nWnX
            WUD7qXXzAont4yH5azlC0O0mLcJgFsrOomHgCznJh1ODJec1SbIJSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T03:05:00Z"
    mac: ENC[AES256_GCM,data:Szxiaf1sbyiK+a7/GWnGBTfU1QDd1dOcQCLA5OleQ87kkrJq1Sl9tt7xOxv+3/ZSelVV9MFEIrJ4KuBdoIn6lN4J6xlNyJcjhg0QX+ci9VUTtKq3+BvY1B5oLhsBeiNjIC0J1/O0gqtXyB90U3T3pQG01ovjhZvv0poq7LUEmjA=,iv:LC17gLYueDeraff2ueYigx2LMGOPvApqddKplCH02sk=,tag:eqzCEghG8sKWalLqyXBsMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
