---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-grafana-db
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    storageClass: "openebs-hostpath"
    size: 5Gi
  walStorage:
    storageClass: "openebs-hostpath"
    size: 5Gi
  databases:
    - name: grafana
  users:
    - name: grafana_user
      databases: grafana
  connections:
    - name: grafana-db
      user: grafana_user
      passwordSecret:
        name: grafana-db-secret
        key: password
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-db-service
  namespace: cnpg-system
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: cluster-grafana-db
