---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-grafana-db
  namespace: cnpg-system
spec:
  instances: 1
  storage:
    storageClass: "openebs-hostpath"
    size: 5Gi
  walStorage:
    storageClass: "openebs-hostpath"
    size: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-db-service
  namespace: cnpg-system
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: cluster-grafana-db
---
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-db-init
  namespace: cnpg-system
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:16
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-db-secret
                key: password
        command: ["psql"]
        args:
          - "--host=cluster-grafana-db"
          - "--username=postgres"   # Adjust as per your setup
          - "--command=CREATE DATABASE grafana; CREATE USER grafana_user WITH ENCRYPTED PASSWORD '${GF_DATABASE_PASSWORD}'; GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana_user;"
      restartPolicy: OnFailure
