---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.sops.yaml
  - ./dashboard/ks.yaml
  - ./placar-db/ks.yaml
  #- ./api/ks.yaml
  #- ./server/ks.yaml
