apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-secret
    namespace: placaron
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ON3ykIrsAxEH4dtXGiKnBIHxQHbCy96Vg69MMEM1YTduI5eqzzXgTyYhOyQwUZA5Ed8noyGAluCYmN2OoZ7na08cXBUKBCuuJn6+gdBUlBV2KQU0mKY41zuHbRAHL0rj8EjeYuA67xvoCsL6,iv:ttjnQ2lD3nwwHgINFVHh4cGFGvM555FGFvkeL/Q5ZLk=,tag:YJoIAU1wxzBEkL7/j8Li8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydVN6czRmcGxpaU9vb09O
            MlZWQnRBZW9KcFZPUkRsRGxlUGQ5T25ZM2dVCnd1VnhKNVBaZmtGV0xaZFpPVE1G
            ZzhIbVFYSGw5dW50RUFnRjZrayt0RVEKLS0tIHh6YSszRXozOCtVakxZK29KSnBi
            MEFMSE5TT3lqTkxZaDEvdXZIdlVaRlkKIJK9o1UyseYMq2wbVlBY4IDvdy/Rj2Ly
            mfJjVrQ6wuDgCpno14tLAe1f0TE73W0FJeuSGJ6tvqCOwfc5N29Fkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T20:56:55Z"
    mac: ENC[AES256_GCM,data:bvugLMD3gNi8EtXwm5zy5mljXErLCz2CMS1GWEbNZj/QIxYT+fNL4qFqFc9idb4o3Q8EPOBkEVhLPEKsw/FY4L7A+wUzcqY5z9XU6h/xq7b9KF99zvYHd9CNgwIXsXdMFzJMswzU2sNFAfwVkD2hXvlRhZlBaGKoWuLVak2ZNcc=,iv:Pd/DaK2pd+23vx4LBeDV5CtXydzhidzsLlslF7he2xo=,tag:JQzHYm/baDJ7tFPqZv5zMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
