---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  config.yml: |
    bolt-path: /var/lib/influxdb2/influxd.bolt
    engine-path: /var/lib/influxdb2/engine
    http-bind-address: :8086
    query-concurrency: 10
    query-queue-size: 10
    storage-retention-check-interval: 30m
    storage-wal-fsync-delay: 0s
