apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VtzD31HVbPnRM4ThRePwKnc0dlauu5JOVLGXsFGudhDddQ795q9qrw==,iv:7xFb87D+lrxadA+munilF4CKyqieJH8sewDvY9ENlTE=,tag:TQtmI4zRPKvibcfyDfkZ3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17g055kax0mcdalkyh79epfjh7g4ws2v6h638mugdkyrngqydp3fsx06j8t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbmxWeGwvVzJVUTNTOVJB
            V3oxOGJRamc1WU1kTnFLWjltN1hOOUp2Z25nCjc4ZVVMUUhrZUE2dGVVNDZtV0U2
            c2J0NS8zMnRzOWg1MFlEMXRiZW11eWcKLS0tIHJrM0toMHlzRyt2a05NU3dRaXkx
            ODBvUytHd3EyUlFtMjl1V1pZUG1BR1EKRm5a0yagkY6cbQ6ZlOjaME9fel71yeAP
            xHN6xiN8cincPDGREjMGvR1FSZYx6SkVcZUpLXx0FLH5uaWyB6CKFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T22:20:29Z"
    mac: ENC[AES256_GCM,data:iNid18DrE2Yeuel4+zdIEoQ4bJt6USNIqXYAgWv6CVA3ILeBGIoz/DiDwTmkf7EqTS32+fLpGvKKIBE7oBYkXe+v/dtNWsfonRWZbHckentfY1sUYhUzC2ojUon4J/ZYUK4+FFtu9Qpoy92vnaCqEFjVGJLV+mUA9aD3lKpYXos=,iv:chfq+kwSjxLxcuW9I9eaRVmryE7CY8Trja56NmPYNX4=,tag:2YCqGDVZ2T3rH745VXEJaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
